# https://docs.spring.io/spring-boot/docs/2.5.6/reference/htmlsingle/#features.external-config.yaml
spring:
  application:
    name: Azure AD B2C Custom Policy Designer
  main:
    banner-mode: off
  servlet:
    # https://docs.spring.io/spring-boot/docs/2.5.6/reference/htmlsingle/#howto.spring-mvc.multipart-file-uploads
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200KB
      max-request-size: 1MB
# https://docs.spring.io/spring-boot/docs/2.5.6/reference/htmlsingle/#application-properties.server
server:
  error:
    include-message: always

custom-policy-settings:
  schema-definition:
    # https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/issues/62
    # https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/issues/71
    local: TrustFrameworkPolicy_0.3.0.0.xsd
    web: https://raw.githubusercontent.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/master/TrustFrameworkPolicy_0.3.0.0.xsd
